/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WissenRouteImport } from './routes/wissen'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as StromGasRouteImport } from './routes/strom-gas'
import { Route as StromRouteImport } from './routes/strom'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as MitarbeiterRouteImport } from './routes/mitarbeiter'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GewerbestromRouteImport } from './routes/gewerbestrom'
import { Route as GewerbegasRouteImport } from './routes/gewerbegas'
import { Route as GasRouteImport } from './routes/gas'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DankeRouteImport } from './routes/danke'
import { Route as AngebotRouteImport } from './routes/angebot'
import { Route as AblaufRouteImport } from './routes/ablauf'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MitarbeiterIndexRouteImport } from './routes/mitarbeiter.index'
import { Route as WissenSlugRouteImport } from './routes/wissen.$slug'
import { Route as MitarbeiterWiedervorlageRouteImport } from './routes/mitarbeiter.wiedervorlage'
import { Route as MitarbeiterVorlagenRouteImport } from './routes/mitarbeiter.vorlagen'
import { Route as MitarbeiterTeamRouteImport } from './routes/mitarbeiter.team'
import { Route as MitarbeiterTarifeRouteImport } from './routes/mitarbeiter.tarife'
import { Route as MitarbeiterStatistikenRouteImport } from './routes/mitarbeiter.statistiken'
import { Route as MitarbeiterLoginRouteImport } from './routes/mitarbeiter.login'
import { Route as MitarbeiterLeadsRouteImport } from './routes/mitarbeiter.leads'
import { Route as MitarbeiterKundenRouteImport } from './routes/mitarbeiter.kunden'
import { Route as MitarbeiterEinstellungenRouteImport } from './routes/mitarbeiter.einstellungen'
import { Route as MitarbeiterDashboardRouteImport } from './routes/mitarbeiter.dashboard'
import { Route as MitarbeiterAnbieterRouteImport } from './routes/mitarbeiter.anbieter'
import { Route as MitarbeiterLeadsIdRouteImport } from './routes/mitarbeiter.leads.$id'

const WissenRoute = WissenRouteImport.update({
  id: '/wissen',
  path: '/wissen',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const StromGasRoute = StromGasRouteImport.update({
  id: '/strom-gas',
  path: '/strom-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const StromRoute = StromRouteImport.update({
  id: '/strom',
  path: '/strom',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const MitarbeiterRoute = MitarbeiterRouteImport.update({
  id: '/mitarbeiter',
  path: '/mitarbeiter',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GewerbestromRoute = GewerbestromRouteImport.update({
  id: '/gewerbestrom',
  path: '/gewerbestrom',
  getParentRoute: () => rootRouteImport,
} as any)
const GewerbegasRoute = GewerbegasRouteImport.update({
  id: '/gewerbegas',
  path: '/gewerbegas',
  getParentRoute: () => rootRouteImport,
} as any)
const GasRoute = GasRouteImport.update({
  id: '/gas',
  path: '/gas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const DankeRoute = DankeRouteImport.update({
  id: '/danke',
  path: '/danke',
  getParentRoute: () => rootRouteImport,
} as any)
const AngebotRoute = AngebotRouteImport.update({
  id: '/angebot',
  path: '/angebot',
  getParentRoute: () => rootRouteImport,
} as any)
const AblaufRoute = AblaufRouteImport.update({
  id: '/ablauf',
  path: '/ablauf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MitarbeiterIndexRoute = MitarbeiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const WissenSlugRoute = WissenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WissenRoute,
} as any)
const MitarbeiterWiedervorlageRoute =
  MitarbeiterWiedervorlageRouteImport.update({
    id: '/wiedervorlage',
    path: '/wiedervorlage',
    getParentRoute: () => MitarbeiterRoute,
  } as any)
const MitarbeiterVorlagenRoute = MitarbeiterVorlagenRouteImport.update({
  id: '/vorlagen',
  path: '/vorlagen',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterTeamRoute = MitarbeiterTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterTarifeRoute = MitarbeiterTarifeRouteImport.update({
  id: '/tarife',
  path: '/tarife',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterStatistikenRoute = MitarbeiterStatistikenRouteImport.update({
  id: '/statistiken',
  path: '/statistiken',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterLoginRoute = MitarbeiterLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterLeadsRoute = MitarbeiterLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterKundenRoute = MitarbeiterKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterEinstellungenRoute =
  MitarbeiterEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => MitarbeiterRoute,
  } as any)
const MitarbeiterDashboardRoute = MitarbeiterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterAnbieterRoute = MitarbeiterAnbieterRouteImport.update({
  id: '/anbieter',
  path: '/anbieter',
  getParentRoute: () => MitarbeiterRoute,
} as any)
const MitarbeiterLeadsIdRoute = MitarbeiterLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MitarbeiterLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/angebot': typeof AngebotRoute
  '/danke': typeof DankeRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/gas': typeof GasRoute
  '/gewerbegas': typeof GewerbegasRoute
  '/gewerbestrom': typeof GewerbestromRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitarbeiter': typeof MitarbeiterRouteWithChildren
  '/service': typeof ServiceRoute
  '/solar': typeof SolarRoute
  '/strom': typeof StromRoute
  '/strom-gas': typeof StromGasRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/mitarbeiter/anbieter': typeof MitarbeiterAnbieterRoute
  '/mitarbeiter/dashboard': typeof MitarbeiterDashboardRoute
  '/mitarbeiter/einstellungen': typeof MitarbeiterEinstellungenRoute
  '/mitarbeiter/kunden': typeof MitarbeiterKundenRoute
  '/mitarbeiter/leads': typeof MitarbeiterLeadsRouteWithChildren
  '/mitarbeiter/login': typeof MitarbeiterLoginRoute
  '/mitarbeiter/statistiken': typeof MitarbeiterStatistikenRoute
  '/mitarbeiter/tarife': typeof MitarbeiterTarifeRoute
  '/mitarbeiter/team': typeof MitarbeiterTeamRoute
  '/mitarbeiter/vorlagen': typeof MitarbeiterVorlagenRoute
  '/mitarbeiter/wiedervorlage': typeof MitarbeiterWiedervorlageRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/mitarbeiter/': typeof MitarbeiterIndexRoute
  '/mitarbeiter/leads/$id': typeof MitarbeiterLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/angebot': typeof AngebotRoute
  '/danke': typeof DankeRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/gas': typeof GasRoute
  '/gewerbegas': typeof GewerbegasRoute
  '/gewerbestrom': typeof GewerbestromRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/service': typeof ServiceRoute
  '/solar': typeof SolarRoute
  '/strom': typeof StromRoute
  '/strom-gas': typeof StromGasRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/mitarbeiter/anbieter': typeof MitarbeiterAnbieterRoute
  '/mitarbeiter/dashboard': typeof MitarbeiterDashboardRoute
  '/mitarbeiter/einstellungen': typeof MitarbeiterEinstellungenRoute
  '/mitarbeiter/kunden': typeof MitarbeiterKundenRoute
  '/mitarbeiter/leads': typeof MitarbeiterLeadsRouteWithChildren
  '/mitarbeiter/login': typeof MitarbeiterLoginRoute
  '/mitarbeiter/statistiken': typeof MitarbeiterStatistikenRoute
  '/mitarbeiter/tarife': typeof MitarbeiterTarifeRoute
  '/mitarbeiter/team': typeof MitarbeiterTeamRoute
  '/mitarbeiter/vorlagen': typeof MitarbeiterVorlagenRoute
  '/mitarbeiter/wiedervorlage': typeof MitarbeiterWiedervorlageRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/mitarbeiter': typeof MitarbeiterIndexRoute
  '/mitarbeiter/leads/$id': typeof MitarbeiterLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/angebot': typeof AngebotRoute
  '/danke': typeof DankeRoute
  '/datenschutz': typeof DatenschutzRoute
  '/faq': typeof FaqRoute
  '/gas': typeof GasRoute
  '/gewerbegas': typeof GewerbegasRoute
  '/gewerbestrom': typeof GewerbestromRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitarbeiter': typeof MitarbeiterRouteWithChildren
  '/service': typeof ServiceRoute
  '/solar': typeof SolarRoute
  '/strom': typeof StromRoute
  '/strom-gas': typeof StromGasRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/mitarbeiter/anbieter': typeof MitarbeiterAnbieterRoute
  '/mitarbeiter/dashboard': typeof MitarbeiterDashboardRoute
  '/mitarbeiter/einstellungen': typeof MitarbeiterEinstellungenRoute
  '/mitarbeiter/kunden': typeof MitarbeiterKundenRoute
  '/mitarbeiter/leads': typeof MitarbeiterLeadsRouteWithChildren
  '/mitarbeiter/login': typeof MitarbeiterLoginRoute
  '/mitarbeiter/statistiken': typeof MitarbeiterStatistikenRoute
  '/mitarbeiter/tarife': typeof MitarbeiterTarifeRoute
  '/mitarbeiter/team': typeof MitarbeiterTeamRoute
  '/mitarbeiter/vorlagen': typeof MitarbeiterVorlagenRoute
  '/mitarbeiter/wiedervorlage': typeof MitarbeiterWiedervorlageRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/mitarbeiter/': typeof MitarbeiterIndexRoute
  '/mitarbeiter/leads/$id': typeof MitarbeiterLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ablauf'
    | '/angebot'
    | '/danke'
    | '/datenschutz'
    | '/faq'
    | '/gas'
    | '/gewerbegas'
    | '/gewerbestrom'
    | '/impressum'
    | '/kontakt'
    | '/mitarbeiter'
    | '/service'
    | '/solar'
    | '/strom'
    | '/strom-gas'
    | '/ueber-uns'
    | '/widerruf'
    | '/wissen'
    | '/mitarbeiter/anbieter'
    | '/mitarbeiter/dashboard'
    | '/mitarbeiter/einstellungen'
    | '/mitarbeiter/kunden'
    | '/mitarbeiter/leads'
    | '/mitarbeiter/login'
    | '/mitarbeiter/statistiken'
    | '/mitarbeiter/tarife'
    | '/mitarbeiter/team'
    | '/mitarbeiter/vorlagen'
    | '/mitarbeiter/wiedervorlage'
    | '/wissen/$slug'
    | '/mitarbeiter/'
    | '/mitarbeiter/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ablauf'
    | '/angebot'
    | '/danke'
    | '/datenschutz'
    | '/faq'
    | '/gas'
    | '/gewerbegas'
    | '/gewerbestrom'
    | '/impressum'
    | '/kontakt'
    | '/service'
    | '/solar'
    | '/strom'
    | '/strom-gas'
    | '/ueber-uns'
    | '/widerruf'
    | '/wissen'
    | '/mitarbeiter/anbieter'
    | '/mitarbeiter/dashboard'
    | '/mitarbeiter/einstellungen'
    | '/mitarbeiter/kunden'
    | '/mitarbeiter/leads'
    | '/mitarbeiter/login'
    | '/mitarbeiter/statistiken'
    | '/mitarbeiter/tarife'
    | '/mitarbeiter/team'
    | '/mitarbeiter/vorlagen'
    | '/mitarbeiter/wiedervorlage'
    | '/wissen/$slug'
    | '/mitarbeiter'
    | '/mitarbeiter/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/ablauf'
    | '/angebot'
    | '/danke'
    | '/datenschutz'
    | '/faq'
    | '/gas'
    | '/gewerbegas'
    | '/gewerbestrom'
    | '/impressum'
    | '/kontakt'
    | '/mitarbeiter'
    | '/service'
    | '/solar'
    | '/strom'
    | '/strom-gas'
    | '/ueber-uns'
    | '/widerruf'
    | '/wissen'
    | '/mitarbeiter/anbieter'
    | '/mitarbeiter/dashboard'
    | '/mitarbeiter/einstellungen'
    | '/mitarbeiter/kunden'
    | '/mitarbeiter/leads'
    | '/mitarbeiter/login'
    | '/mitarbeiter/statistiken'
    | '/mitarbeiter/tarife'
    | '/mitarbeiter/team'
    | '/mitarbeiter/vorlagen'
    | '/mitarbeiter/wiedervorlage'
    | '/wissen/$slug'
    | '/mitarbeiter/'
    | '/mitarbeiter/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblaufRoute: typeof AblaufRoute
  AngebotRoute: typeof AngebotRoute
  DankeRoute: typeof DankeRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FaqRoute: typeof FaqRoute
  GasRoute: typeof GasRoute
  GewerbegasRoute: typeof GewerbegasRoute
  GewerbestromRoute: typeof GewerbestromRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MitarbeiterRoute: typeof MitarbeiterRouteWithChildren
  ServiceRoute: typeof ServiceRoute
  SolarRoute: typeof SolarRoute
  StromRoute: typeof StromRoute
  StromGasRoute: typeof StromGasRoute
  UeberUnsRoute: typeof UeberUnsRoute
  WiderrufRoute: typeof WiderrufRoute
  WissenRoute: typeof WissenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wissen': {
      id: '/wissen'
      path: '/wissen'
      fullPath: '/wissen'
      preLoaderRoute: typeof WissenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strom-gas': {
      id: '/strom-gas'
      path: '/strom-gas'
      fullPath: '/strom-gas'
      preLoaderRoute: typeof StromGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strom': {
      id: '/strom'
      path: '/strom'
      fullPath: '/strom'
      preLoaderRoute: typeof StromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitarbeiter': {
      id: '/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter'
      preLoaderRoute: typeof MitarbeiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gewerbestrom': {
      id: '/gewerbestrom'
      path: '/gewerbestrom'
      fullPath: '/gewerbestrom'
      preLoaderRoute: typeof GewerbestromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gewerbegas': {
      id: '/gewerbegas'
      path: '/gewerbegas'
      fullPath: '/gewerbegas'
      preLoaderRoute: typeof GewerbegasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas': {
      id: '/gas'
      path: '/gas'
      fullPath: '/gas'
      preLoaderRoute: typeof GasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danke': {
      id: '/danke'
      path: '/danke'
      fullPath: '/danke'
      preLoaderRoute: typeof DankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebot': {
      id: '/angebot'
      path: '/angebot'
      fullPath: '/angebot'
      preLoaderRoute: typeof AngebotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ablauf': {
      id: '/ablauf'
      path: '/ablauf'
      fullPath: '/ablauf'
      preLoaderRoute: typeof AblaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitarbeiter/': {
      id: '/mitarbeiter/'
      path: '/'
      fullPath: '/mitarbeiter/'
      preLoaderRoute: typeof MitarbeiterIndexRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/wissen/$slug': {
      id: '/wissen/$slug'
      path: '/$slug'
      fullPath: '/wissen/$slug'
      preLoaderRoute: typeof WissenSlugRouteImport
      parentRoute: typeof WissenRoute
    }
    '/mitarbeiter/wiedervorlage': {
      id: '/mitarbeiter/wiedervorlage'
      path: '/wiedervorlage'
      fullPath: '/mitarbeiter/wiedervorlage'
      preLoaderRoute: typeof MitarbeiterWiedervorlageRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/vorlagen': {
      id: '/mitarbeiter/vorlagen'
      path: '/vorlagen'
      fullPath: '/mitarbeiter/vorlagen'
      preLoaderRoute: typeof MitarbeiterVorlagenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/team': {
      id: '/mitarbeiter/team'
      path: '/team'
      fullPath: '/mitarbeiter/team'
      preLoaderRoute: typeof MitarbeiterTeamRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/tarife': {
      id: '/mitarbeiter/tarife'
      path: '/tarife'
      fullPath: '/mitarbeiter/tarife'
      preLoaderRoute: typeof MitarbeiterTarifeRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/statistiken': {
      id: '/mitarbeiter/statistiken'
      path: '/statistiken'
      fullPath: '/mitarbeiter/statistiken'
      preLoaderRoute: typeof MitarbeiterStatistikenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/login': {
      id: '/mitarbeiter/login'
      path: '/login'
      fullPath: '/mitarbeiter/login'
      preLoaderRoute: typeof MitarbeiterLoginRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/leads': {
      id: '/mitarbeiter/leads'
      path: '/leads'
      fullPath: '/mitarbeiter/leads'
      preLoaderRoute: typeof MitarbeiterLeadsRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/kunden': {
      id: '/mitarbeiter/kunden'
      path: '/kunden'
      fullPath: '/mitarbeiter/kunden'
      preLoaderRoute: typeof MitarbeiterKundenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/einstellungen': {
      id: '/mitarbeiter/einstellungen'
      path: '/einstellungen'
      fullPath: '/mitarbeiter/einstellungen'
      preLoaderRoute: typeof MitarbeiterEinstellungenRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/dashboard': {
      id: '/mitarbeiter/dashboard'
      path: '/dashboard'
      fullPath: '/mitarbeiter/dashboard'
      preLoaderRoute: typeof MitarbeiterDashboardRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/anbieter': {
      id: '/mitarbeiter/anbieter'
      path: '/anbieter'
      fullPath: '/mitarbeiter/anbieter'
      preLoaderRoute: typeof MitarbeiterAnbieterRouteImport
      parentRoute: typeof MitarbeiterRoute
    }
    '/mitarbeiter/leads/$id': {
      id: '/mitarbeiter/leads/$id'
      path: '/$id'
      fullPath: '/mitarbeiter/leads/$id'
      preLoaderRoute: typeof MitarbeiterLeadsIdRouteImport
      parentRoute: typeof MitarbeiterLeadsRoute
    }
  }
}

interface MitarbeiterLeadsRouteChildren {
  MitarbeiterLeadsIdRoute: typeof MitarbeiterLeadsIdRoute
}

const MitarbeiterLeadsRouteChildren: MitarbeiterLeadsRouteChildren = {
  MitarbeiterLeadsIdRoute: MitarbeiterLeadsIdRoute,
}

const MitarbeiterLeadsRouteWithChildren =
  MitarbeiterLeadsRoute._addFileChildren(MitarbeiterLeadsRouteChildren)

interface MitarbeiterRouteChildren {
  MitarbeiterAnbieterRoute: typeof MitarbeiterAnbieterRoute
  MitarbeiterDashboardRoute: typeof MitarbeiterDashboardRoute
  MitarbeiterEinstellungenRoute: typeof MitarbeiterEinstellungenRoute
  MitarbeiterKundenRoute: typeof MitarbeiterKundenRoute
  MitarbeiterLeadsRoute: typeof MitarbeiterLeadsRouteWithChildren
  MitarbeiterLoginRoute: typeof MitarbeiterLoginRoute
  MitarbeiterStatistikenRoute: typeof MitarbeiterStatistikenRoute
  MitarbeiterTarifeRoute: typeof MitarbeiterTarifeRoute
  MitarbeiterTeamRoute: typeof MitarbeiterTeamRoute
  MitarbeiterVorlagenRoute: typeof MitarbeiterVorlagenRoute
  MitarbeiterWiedervorlageRoute: typeof MitarbeiterWiedervorlageRoute
  MitarbeiterIndexRoute: typeof MitarbeiterIndexRoute
}

const MitarbeiterRouteChildren: MitarbeiterRouteChildren = {
  MitarbeiterAnbieterRoute: MitarbeiterAnbieterRoute,
  MitarbeiterDashboardRoute: MitarbeiterDashboardRoute,
  MitarbeiterEinstellungenRoute: MitarbeiterEinstellungenRoute,
  MitarbeiterKundenRoute: MitarbeiterKundenRoute,
  MitarbeiterLeadsRoute: MitarbeiterLeadsRouteWithChildren,
  MitarbeiterLoginRoute: MitarbeiterLoginRoute,
  MitarbeiterStatistikenRoute: MitarbeiterStatistikenRoute,
  MitarbeiterTarifeRoute: MitarbeiterTarifeRoute,
  MitarbeiterTeamRoute: MitarbeiterTeamRoute,
  MitarbeiterVorlagenRoute: MitarbeiterVorlagenRoute,
  MitarbeiterWiedervorlageRoute: MitarbeiterWiedervorlageRoute,
  MitarbeiterIndexRoute: MitarbeiterIndexRoute,
}

const MitarbeiterRouteWithChildren = MitarbeiterRoute._addFileChildren(
  MitarbeiterRouteChildren,
)

interface WissenRouteChildren {
  WissenSlugRoute: typeof WissenSlugRoute
}

const WissenRouteChildren: WissenRouteChildren = {
  WissenSlugRoute: WissenSlugRoute,
}

const WissenRouteWithChildren =
  WissenRoute._addFileChildren(WissenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblaufRoute: AblaufRoute,
  AngebotRoute: AngebotRoute,
  DankeRoute: DankeRoute,
  DatenschutzRoute: DatenschutzRoute,
  FaqRoute: FaqRoute,
  GasRoute: GasRoute,
  GewerbegasRoute: GewerbegasRoute,
  GewerbestromRoute: GewerbestromRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MitarbeiterRoute: MitarbeiterRouteWithChildren,
  ServiceRoute: ServiceRoute,
  SolarRoute: SolarRoute,
  StromRoute: StromRoute,
  StromGasRoute: StromGasRoute,
  UeberUnsRoute: UeberUnsRoute,
  WiderrufRoute: WiderrufRoute,
  WissenRoute: WissenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
